# Generated by Django 5.2.4 on 2025-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.IntegerField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
